version: '3.9'
services:
  postgres:
    container_name: ekw-customer-billing-database
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ekw-customer-billing
    ports:
      - '5432:5432'
